[package]
name = "errors"
version = "0.1.0"
authors = ["gauravsaini"]
edition = "2018"

[lib]
name = "errors"
path = "src/lib.rs"

[[bin]]
name = "errors"
path = "src/main.rs"

[dependencies]
serde = "1.0.91"
serde_derive = "1.0.91"
serde_json = "1.0.39"
failure = "0.1.8"
